services:
  app:
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: file_cloud
      MYSQL_PASSWORD: Todor1990///
      MYSQL_DB: file_cloud
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: file_cloud
      MYSQL_PASSWORD: Todor1990///
      MYSQL_DATABASE: file_cloud

volumes:
  todo-mysql-data: